### ISSUE TITLE
Toggle keypad lock on/off

### ISSUE THREAD

**Issue by wildekek** [wildekek/riden-esphome#1]
When connected over MODBUS the device automatically locks the physical keypad. Would be nice to be able to toggle that from Home Assistant, perhaps by disconnecting temporarily?

**Comment by MDBInd** [comment]
I am using the UniSoft RD60065_V1.41.1h custom firmware for my RD6006P and this functionality can be disabled in the settings with "Skip keys lock".

https://www.eevblog.com/forum/testgear/ruideng-riden-rd6006-dc-power-supply/950/
https://www.eevblog.com/forum/testgear/custom-firmware-reference-document-for-riden-rd60xx-power-supplies/

**Comment by wildekek** [comment]
Ah, nice find. I kinda lost track on Unisofts development since he doesn't use Github, but I'll try that out.

**Comment by wildekek** [comment]
Confirmed that "Skip keys lock" in UniSoft FW > 1.37.1 fixes this.
