### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by d-schultz** [wildekek/riden-esphome#6]
Hi, could you please give some instructions for setting this up? 

- Is the yaml for home assistant? 
- Do I only need to add this to the configuration.yaml and then the device is integrated in HA? 
- Does it connect to the Wifi that HA uses automatically, or how is a wifi connection established?
- What to do with the FTDI adapter?

**Comment by wildekek** [comment]
I added a new repo with instructions on how to update the firmware on the Riden power supplies to the latest UniSoft firmware: https://github.com/wildekek/riden-firmware-unisoft

**Comment by wildekek** [comment]
Hi @d-schultz , I updated the README and I think it answers your questions. Please let me know what you think, then I can update the instructions and/or close this issue.
